### ISSUE TITLE
Som Admin vill jag kunna skapa en ny kund

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#10]
![Image](https://github.com/user-attachments/assets/a9615727-5839-4533-b6fd-1070ed00d425)

## Tasks

- [ ] Skapa ett formulär för att kunna lägga till en kund
  - Formuläret ska innehålla fält och dessa ska bindas efter KundModellen

- [ ] Skapa validering för formuläret
  - Formuläret ska ha korrekt validering för email
  - Formuläret ska ha korrekt validering för telefonnummer
  - Formuläret ska ha korrekt validering för tvingande fält
 
- [ ] Skapa en submit-knapp i formuläret
  - Knappen ska påkalla Create funktionen i AccountProvider

- [ ] Visa statuskoder som meddelande för admin
  - Meddelandena ska vara i klar text t.ex vid retur av statuskod 201 = "Tilläggning lyckades" eller 401 = "Du är inte auktoriserad"

## Acceptanskriterier
1. En admin ska kunna lägga till en ny kund i databasen
2. Alla fälten ska valideras så att det kommer in korrekt i databasen
3. Meddelanden ska visas för admin vid olika fall

### **Lyckad tilläggning**
  Förutsättningar: 
  - Admin väljer att lägga till en ny kund via formuläret
  - Admin trycker på submit-knappen
          
**Steg**
1. Fyll i alla värden korrekt i formuläret
2. Klicka på submit knappen så formuläret skickas iväg
           
**Förväntat resultat**
  - En kund har lagts till i databasen
  - Ett meddelande visas som informerar admin att kunden har skapats

### **Ett värde är inte korrekt**
Förutsättningar: 
  - Admin väljer att lägga till en ny kund via formuläret
  - Admin skriver in fel email/telefonnr eller inte fyller i ett tvingande fält

**Steg**
  1. Fyll i värden
  2. Ett av värdena i fältet är inkorrekt (t.ex email utan "@")

**Förväntat resultat**
  - Ett felmeddelande visas som informerar admin om vilket/vilka värde som inte är korrekt och hur det ska skrivas för att validering ska gå igenom
  - Admin ska ha möjlighet att rätta till fältet utan att allt försvinner
