### ISSUE TITLE
Som administratör vill jag kunna se detaljerad information om en specifik order för granskning

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#14]
### **Tasks:**

- [x] Skapa en function som retunerar en order utifrån order-ID från orderprovider
---
- [x] Implementera en knapp i ordertabellen som gör att admin kan klicka för att visa detaljer om specefik order 
---
- [x] Skapa en vy i adminpanelen som visar detaljerad orderinformation, visa all relevant information som: order-ID, Kudens kontaktinfo, Lista över beställda produkter, datum, status och totalbelopp
---
- [x] Visa en laddningsindikator medans orderinformationen hämtas 
---
- [x] Implementera logik för att visa felmeddelande om något går fel när order hämtas från API
---

### **Testfallsbeskrivningar:**

- [ ] Testfall 1: Lyckad visning av orderdetaljer

_Förutsättningar:_
- Admin är inloggad i adminpanelen
- Det finns en order att granska i systemet

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till orderhantering
- Klicka på en specefik order för att visa detaljer

_Förväntat resultat:_
- Detaljerat information om orden visas

---

- [ ] Testfall 2: Misslyckad visning av orderdetaljer

_Förutsättningar:_
- Admin är inloggad i adminpanelen
- Det finns en order att granska i systemet
- Serverfel från orderprovider

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till orderhantering
- Klicka på en specefik order för att visa detaljer

_Förväntat resultat:_
- Ett felmeddelande visas som informerar om att orden inte kunde hämtas

---

### **Acceptanskriterier:**

  1. Administratören kan klicka på en specifik order för att se detaljerad information om den.
  2. All relevant information om ordern visas tydligt, inklusive kundinformation, beställda produkter, datum, leveransadress, totalbelopp, och orderstatus.
  3. Om ett fel inträffar (t.ex. order-ID är ogiltigt eller systemfel), visas ett relevant felmeddelande till administratören.
  4. En laddningsindikator visas medan orderinformationen hämtas, och informationen visas utan att administratören behöver uppdatera sidan.
