### ISSUE TITLE
Som administratör vill jag kunna avbryta en order för att stoppa behandlingen

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#15]
### **Tasks:**

- [ ] Skapa en function som hanterar avbryt utifrån order-ID till orderprovider
---
- [ ] Lägg till en "Avbryt order" knapp i orderdetaljvyn, för varje order som är i ett avbrytbart tillstånd.
---
- [ ] Implementera en bekräftelseruta som frågar om man verkligen vill avbryta ordern.
---
- [ ] Hantera response meddelanden från API med exempelvis alerts.
---
- [ ] Uppdatera gränssnittet om avbrytningen lyckades. 
---

### **Testfallsbeskrivningar:**

- [ ] Testfall 1: Lyckad avbrytning av order

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns en order som är i ett avbrytbart tillstånd ( "Bearbetas")

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till orderdetails
- Admin klickar på "Avbryt order"
- En bekräfelse visas om man verkligen vill avbryta ordern
- Admin klickar "Ja" för att bekräfta.
- Förfrågan till API skickas.

_Förväntat resultat:_
- Orderstatus uppdateras till Avbruten
- Ett meddelande visas som bekräftar att ordern har avbrutits framgångsrikt

---

- [ ] Testfall 2: Ingen avbrytning vid avslag

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns en order som är i ett avbrytbart tillstånd ( "Bearbetas")

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till orderdetails
- Admin klickar på "Avbryt order"
- En bekräfelse visas om man verkligen vill avbryta ordern
- Admin klickar "Nej" för att bekräfta.

_Förväntat resultat:_
- Ingen förfrågan skickas till API
- Orderstatus förblir oförändrad

---

- [ ] Testfall 3: Avbrytning misslyckas på grund av nätverksfel

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns en order som är i ett avbrytbart tillstånd (t.ex. status "Bearbetas").
- Ett nätverksfel eller serverfel inträffar vid försök att kontakta API

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till orderdetails
- Admin klickar på "Avbryt order"
- En bekräfelse visas om man verkligen vill avbryta ordern
- Admin klickar "Ja" för att bekräfta.
- Förfrågan till API skickas, men ett nätverksfel uppstår

_Förväntat resultat:_
- Ett felmeddelande visas som informerar om vad som har gått fel
- Orderstatus förblir oförändrad

---

- [ ] Testfall 4: Misslyckad avbrytning av order på grund av slutförd status

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns en order med status "Slutförd" (eller en status som inte kan avbrytas).

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till orderdetails
- Admin klickar på "Avbryt order"
- En bekräfelse visas om man verkligen vill avbryta ordern
- Admin klickar "Ja" för att bekräfta.
- Förfrågan till API skickas

_Förväntat resultat:_
- Ett felmeddelande visas som informerar administratören om att ordern inte kan avbrytas eftersom den redan är slutförd.
- Orderstatus förblir oförändrad

---

### **Acceptanskriterier:**

  1. Lyckad avbrytning 
  2. Ingen avbrytning vid avslag
  3. Misslyckad avbrytning (order redan slutförd)
  5. Felhantering
  6. Tydlig återkoppling i gränssnittet
