### ISSUE TITLE
Som administratör vill jag kunna filtrera ordrar baserat på deras status för att kunna se ordrar i olika stadier

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#16]
![Image](https://github.com/user-attachments/assets/7257416a-d854-4123-9739-ee80fe7513bc)

### **Tasks:**

- [ ] Skapa en function som retunerar ordrar utifrån statusparameter från orderprovider. Inkludera ordernummer, kundnamn, datum, totalbelopp och status.
---
- [ ] Lägg till funktionalitet i tabellen för att administratören ska kunna filtrera efter orderstatus (Alla, Bearbetas, Slutförd).
---
- [ ] Hantera logik för att visa meddelande om inga ordrar finns för vald status.
---

### **Testfallsbeskrivningar:**

- [ ] Testfall 1: Filtret för orderstatus fungerar korrekt

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns ordrar med olika status som "Bearbetas" och "Slutförd"

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering
- Använd filtrering och välj orderstatus "Slutförd"

_Förväntat resultat:_
- Endast ordrar med status "Slutförd" visas i tabellen
- Filtreringen sker utan att sidan laddas om

---

- [ ] Testfall 2: Filtrering fungerar inte korrekt

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns ordrar med olika status
- Systemet misslyckas hämta ordrar utifrån statusparamter (ex serverfel)

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering
- Använd filtrering och välj orderstatus

_Förväntat resultat:_
- Ett felmeddelande visas, till exempel "filtrering misslyckades, försök igen senare".
- Systemet hanterar fel utan att krascha.

---

- [ ] Testfall 3: Filtrera på en status utan matchande ordrar

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns inga ordrar med den valda statusen.

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering
- Använd filtrering och välj orderstatus "" (som inte finns för någon order).

_Förväntat resultat:_
- Ett meddelande visas "inga ordrar matchar vald status".
- Systemet hanterar tomma resultat utan att krascha

---

- [ ] Testfall 4: Återställ filter för att visa alla ordrar igen

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Admin har filtrerat ordrar efter status.

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering
- Klicka på "Alla" för att visa alla ordrar

_Förväntat resultat:_
- Alla ordrar visas oavsett status.

---

### **Acceptanskriterier:**

  1. Admin kan filtrera ordrar efter status
  2. Endast ordrar med den valda statusen visas
  3. Man kan enkelt återställa filtret för att visa alla ordrar
  4. Felmeddelande visas om ingen order matchar vald status
