### ISSUE TITLE
Som administratör vill jag kunna hämta alla ordar för att få en överblick

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#17]
![Image](https://github.com/user-attachments/assets/6a0afa84-6a41-4247-98b4-ddaf06725102)

---

### **Tasks:**

- [x] Skapa en function som retunerar en lista över alla ordrar från orderprovider.
---
- [x] Skapa en vy i adminpanelen där alla ordrar listas i en tabell. Tabellen skall innehålla kolumner för ordernummer, kundnamn, datum, totalbelopp och status.
---
- [x] Hantera sortering av ordrar efter datum.
---
- [x] Hantera logik för att visa felmeddelande om något går fel när ordrarna hämtas.
---

### **Testfallsbeskrivningar:**

- [x] Testfall 1: Lyckad hämtning av alla ordrar

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns flera ordrar i systemet.

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering

_Förväntat resultat:_
- Alla ordrar visas i en tabell
- För varje order ska följande information vara synlig
  - Ordernummer
  - Kunden namn
  - Beställningsdatum
  - Totalbelopp
  - Orderstatus
- Ordrarna är sorterade efter beställningsdatum, där senaste ordrarna visas högst upp.

---

- [x] Testfall 2: Inga ordrar tillgängliga

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns inga ordrar i systemet.

 _Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering

 _Förväntat resultat:_
- Ett meddelande visas "Inga ordrar tillgängliga".
 - Administratören kan se en tom lista utan att systemet kraschar

---

- [x] Testfall 3: Felmeddelande vid misslyckad hämtning av ordrar

_Förutsättningar:_
 - Admin är inloggad i adminpanelen.
- Det uppstår ett fel vid hämtning av ordrar, t.ex. serverfel.

 _Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering

 _Förväntat resultat:_
- Ett felmeddalnde visas som informerar om att något gick fel vid hämtning av ordrar.
- Systemet kan hantera felet utan att krascha.

---

- [x] Testfall 4: Sortering av ordrar efter datum (senaste först)

_Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns flera ordrar med olika datum.

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering
- Kontrollera att ordrarna i tabellen är sorterade efter datum (senaste först)

_Förväntat resultat:_
- Ordrarna är sorterade i fallande ordning efter beställningsdatum, där den senaste ordern visas överst i listan.

---

- [x] Testfall 5: Sortering av ordrar i stigande ordning vid klick på kolumnhuvudet

 _Förutsättningar:_
- Admin är inloggad i adminpanelen.
- Det finns flera ordrar med olika datum.

_Steg:_
- Logga in som admin i adminpanelen
- Navigera till sektionen för orderhantering
- Klicka på kolumnhuvudet för "Datum" för att sortera ordrarna i stigande ordning (äldsta först).

_Förväntat resultat:_
- Ordrarna sorteras i stigande ordning efter beställningsdatum, där den äldsta ordern visas överst i listan..

---

### **Acceptanskriterier:**

  1. Administratören kan hämta alla ordrar
  2. Tabellen visar ordernummer, kundnamn, datum, totalbelopp och status.
  3. Ordrar visas i fallande ordning efter datum.
  4. Sortering av datum vid klick på kolumnhuvudet.
  5. Felmeddelanden visas vid problem med hämtning av ordrar.
