### ISSUE TITLE
Som en Admin vill jag kunna lägga till en produkt

### ISSUE THREAD

**Issue by gammall** [Project-Rika/Rika_Backoffice#19]
# TASKS

- [ ] Task 1: Skapa en vy för att lägga till en produkt
- [ ] Task 2: Skapa ett form som tar in rätt värden utifrån ProduktEntity

# TESTFALLSBESKRIVNING

- [ ] Testfall 1: Lyckat skapande av en produkt

### Förutsättningar:
- Admin är inloggad i adminpanelen
- Det finns en vy för att skapa en ny produkt

### Steg
- Logga in som admin i adminpanelen
- Det finns en knapp "Lägg ny produkt" i adminpanelen
- Det finns en vy för att skapa en produkt

### Förväntat resultat
- En produkt skapas och läggs in korrekt databas

# ACCEPTANSKRITERIE
- Admin kan navigera till produktskapar-vyn
- Admin kan fylla i rätt info om en produkt, lägga till en bild och sedan skapa en produkt
- Produkten ska läggas in i korrekt databas
