### ISSUE TITLE
Som en Admin vill jag kunna generera en rapport för att se produktinformation

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#2]
## Tasks

- [ ] **Task 1: Implementera UI för produktinformationsrapport**
   - Skapa ett användargränssnitt där admin kan ange kriterier för att generera en rapport, exempelvis artikelnummer, produktkategori, lanseringsdatum, eller produktnamn.

- [ ] **Task 2: Implementera API-endpoint för produktinformation**
   - Bygg en endpoint i ReportProvider som returnerar en lista med produkter och alla dess attribut baserat på sökkriterierna som skickats med förfrågan.

- [ ] **Task 3: Bygg en action som kan exportera rapporten till excel.**
   - Det ska finnas en knapp på sidan som man kan trycka på för att ladda ner rapporten i excel-format. 

- [ ] **Task 4: Bygg en action som kan exportera rapporten som en PDF-fil.**
   - Det ska finnas en knapp på sidan som man kan trycka på för att ladda ner rapporten i PDF-format. 

- [ ] **Task 5: Implementera filtrering och sortering av produktinformation**
   - Lägg till möjligheten för admin att filtrera och sortera produktinformation efter olika kriterier, som produktnamn, artikelnummer, produktkatergori osv., förslagsvis genom att klicka på kolumnrubriken.

## Acceptanskriterier
   1. Admin ska kunna få ut en lista med produktinformation baserat på sökkriterier som artikelnummer, produktnamn etc. 
   2. Rapporten ska visa alla olika relevanta attribut som produktnamn, artikelnummer, pris etc.
   3. Det ska gå att filtrera och sortera på relevanta attribut som artikelnummer, produktkategori, lanseringsdatum osv.    
   4. Det ska gå att exportera denna lista till excel.
   5. Det ska gå att exportera denna lista till PDF.

## Testfallsbeskrivningar

- [ ] **Testfall 1: Lyckad rapportgenerering för produktinformation**
   - Förutsättningar: Användaren är inloggad och har åtkomst till rapportgenereringsfunktionen. 
   - Steg:
       1. Navigera till sidan för rapportgenerering. 
       2. Klicka på "Generera rapport".

   - Förväntat resultat: En produktinformationsrapport visas som visar alla artiklar som finns registrerade i databasen.

- [ ] **Testfall 2: Lyckad rapportgenerering för produktinformation baserat på produktkategori**
   - Förutsättningar: Användaren är inloggad och har åtkomst till rapportgenereringsfunktionen. 
   - Steg:
       1. Navigera till sidan för rapportgenerering. 
       2. Välj produktkategori från en drop-down meny på sidan.
       3. Klicka på "Generera rapport".

   - Förväntat resultat: En produktinformationsrapport visas som visar alla artiklar som finns registrerade i databasen som har den valda produktkategorin.

- [ ] **Testfall 3: Lyckad rapportgenerering för produktinformation baserat på produktnamn**
   - Förutsättningar: Användaren är inloggad och har åtkomst till rapportgenereringsfunktionen. 
   - Steg:
       1. Navigera till sidan för rapportgenerering. 
       2. Mata in produktnamnet i ett textfält.
       3. Klicka på "Generera rapport".

   - Förväntat resultat: En produktinformationsrapport visas som visar alla artiklar som finns registrerade i databasen som har hela eller en del av namnet som användaren sökt efter.
