### ISSUE TITLE
som admin vill jag kunna se samtliga produkter

### ISSUE THREAD

**Issue by gammall** [Project-Rika/Rika_Backoffice#20]
![Image](https://github.com/user-attachments/assets/356ea2c1-efb2-4626-8562-00f4af7fae42)

# TASKS
- [x] Skapa en function som returnerar en lista över alla produkter från productprovider.
- [x] Skapa en vy som listar upp alla produkter
- [x] Hantera sortering 
- [x] Skapa en knapp för att kunna ta bort, eller inaktivera en produkt

# TESTFALLSBESKRIVNINGAR

### Förutsättningar:
- Admin är inloggad i adminpanelen
- Det finns flera produkter i systemet

### Steg:
- Logga in som admin i adminpanelen
- Navigera till sektionen för produkthantering

### Förväntat resultat:
- Alla produkter visas i en tabell

#

### Förutsättningar:
- Admin efterfrågar en specifik sortering (ex. dyrast först)

### Steg:
- I listvyn väljer admin vilken sortering som önskas
- Admin klickar på knappen "Sortera"

### Förväntat resultat:
- Produkter sorteras efter önskat utfall

#

### Förutsättningar:
- Admin vill ta bort eller inaktivera en eller flera produkter

### Steg:
- I listvyn finns 2 knappar "Ta bort" "Inaktivera"
- Admin klickar på någon av dem och kan "highlighta" produkter för att sedan antingen ta bort eller inaktivera samtliga "highlightade".

### Förväntat resultat:
- Valda produkter blir antingen ta bort eller inaktiverade.

# ACCEPTANSKRITERIER

- Admin kan hämta samtliga produkter
- Admin kan sortera produkter utifrån önskemål
- Admin kan ta bort eller inaktivera en eller flera produkter
