### ISSUE TITLE
som admin vill jag kunna ta bort en produkt

### ISSUE THREAD

**Issue by gammall** [Project-Rika/Rika_Backoffice#21]
# TASKS
- [ ] Admin ska kunna ta bort en specifik produkt i antingen List-vyn eller i produkt-vyn
- En knapp (papperskorg) som visas i vyn för samtliga produkter och i vyn för en specifik

- [ ] Admin ska kunna inaktivera en specifik produkt i antingen list-vyn eller i produkt-vyn

# ACCEPTANSKRITERIER
1. Admin kan ta bort en specifik produkt från både listvyn samt produktvyn.
2. Admin ska kunna inaktivera en specifik produkt när exempelvis en produkt är slutsåld eller ifall en produkt inte börjat säljas än.

# TEST
- [ ] Testfall 1: Produkt blir borttagen i databasen, alt, inaktiverad på kund-sidan.

## Förutsättningar
- Admin är inloggad i adminpanelen
- Det finns en vy som listar samtliga produkter samt en produktvy (kan vara skapad)
-
