### ISSUE TITLE
Som en Admin vill jag kunna generera en rapport för att se användarbeteende

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#3]
## Tasks

- [ ] **Task 1: Implementera UI för användarbeteenderapport**
   - Skapa ett användargränssnitt där en admin kan ange kriterier som till exempel tidsperiod, datum osv för att generera en rapport för användarbeteende.

- [ ] **Task 2: Implementera logik för hur programmet ska samla in data om antal klick på olika komponenter, antal besökare etc.**

## Acceptanskriterier
   1. Admin ska kunna generera en rapport med användarbeteende.
   2. Rapporten ska visa vilka tider på dygnet sidan har mest trafik. 
   3. Rapporten ska visa hur lång tid användare varit inne på specifika sidor. 
   4. Det ska gå att se hur många klick olika typer av produkter har genererat.

## Testfallsbeskrivningar

- [ ] **Testfall 1: Lyckad rapportgenerering för användarbeteende**
   - Förutsättningar: Användaren är inloggad och har åtkomst till rapportgenereringsfunktionen. 
   - Steg:
       1. Navigera till sidan för rapportgenerering. 
       2. Klicka på "Generera rapport".

   - Förväntat resultat: En rapport för användarbeteende visas på sidan.
