### ISSUE TITLE
Som en Admin vill jag kunna generera en rapport för att se försäljningsstatistik

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#4]
![Image](https://github.com/user-attachments/assets/3d6b6008-1f39-46f4-9870-d9e00a1d3658)
## Tasks

- [ ] **Task 1: Implementera UI för försäljningsstatistik**
   - Skapa ett användargränssnitt där en admin kan ange kriterier som till exempel tidsperiod, artikelkategorier etc. för att generera en försäljningsrapport.

- [ ] **Task 2: Implementerea API-endpoint för försälningsdata**
   - Bygg en endpoint i ReportProvider som tar ut försäljningsstatistik ur databasen. Den måste ta emot sökkriterier som admin anger, så som artikelkategori, tidsperiod osv.

- [ ] **Task 3: Bygg en action som kan exportera rapporten till excel.**
   - Det ska finnas en knapp på sidan som man kan trycka på för att ladda ner rapporten i excel-format. 

- [ ] **Task 4: Bygg en action som kan exportera rapporten som en PDF-fil.**
   - Det ska finnas en knapp på sidan som man kan trycka på för att ladda ner rapporten i PDF-format. 

- [ ] **Task 5: Implementera filtrering och sortering av försäljningsdata**
   - Lägg till möjligheten för admin att filtrera och sortera försäljningsdata efter olika kriterier, som produktnamn, försäljningsvolym, och intäkter.

## Acceptanskriterier
   1. Admin ska kunna få ut en lista med försäljningsstatistik för valda artiklar, artikelkategorier, datum osv. 
   2. Det ska gå att filtrera och sortera på relevanta attribut som artikelnummer, produktkategori, lanseringsdatum osv. 
   4. Det ska gå att exportera denna lista till excel.
   5. Det ska gå att exportera denna lista till PDF.

## Testfallsbeskrivningar

- [ ] **Testfall 1: Lyckad rapportgenerering för försäljning under ett tidsintervall**
   - Förutsättningar: Användaren är inloggad och har åtkomst till rapportgenereringsfunktionen. 
   - Steg:
       1. Navigera till sidan för rapportgenerering. 
       2. Ange ett tidsintervall.
       3. Klicka på "Generera rapport".

   - Förväntat resultat: En försäljningsrapport visas som visar försäljningsvolym och intäkter för det angivna tidsintervallet.

- [ ] **Testfall 2: Lyckad filtrering av rapport efter produktkategori**
   - Förutsättningar: Användaren är inloggad och har genererat en försäljningsrapport. 
   - Steg:
       1. Generera en försäljningsrapport. 
       2. Välj en produktkategori från filtreringsalternativen.
       3. Klicka på "Filtrera".

   - Förväntat resultat: En försäljningsrapport visas som är filtrerad på den valda produktkategorin.

- [ ] **Testfall 3: Export till Excel**
   - Förutsättningar: Användaren är inloggad och har genererat en försäljningsrapport. 
   - Steg:
       1. Generera en försäljningsrapport. 
       2. Klicka på "Exportera till Excel".

   - Förväntat resultat: En excel-fil laddas ner med den eventuellt filtrerade försäljningsrapporten.

- [ ] **Testfall 4: Export till PDF**
   - Förutsättningar: Användaren är inloggad och har genererat en försäljningsrapport. 
   - Steg:
       1. Generera en försäljningsrapport. 
       2. Klicka på "Exportera till PDF".

   - Förväntat resultat: En PDF-fil laddas ner med den eventuellt filtrerade försäljningsrapporten.

- [ ] **Testfall 5: Sortering av försäljningsrapport**
   - Förutsättningar: Användaren är inloggad och har genererat en försäljningsrapport. 
   - Steg:
       1. Generera en försäljningsrapport. 
       2. Klicka på valfri kolumnrubrik för att sortera data i kolumnen stigande eller fallande.

   - Förväntat resultat: Rapporten sorteras efter intäkter i stigande eller fallande ordning.
