### ISSUE TITLE
Som en Admin vill jag kunna se en specifik kund

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#7]
## Tasks

- [ ] Skapa funktionalitet för att hitta en kund
  - Denna ska hittas med hjälp av ett kundId
  - Du ska använda dig av GET funktionen i AccountProvider (Läs readme i AccountProvider)

- [ ] Skapa ett formulär där kundens uppgifter visas
  - Bind korrekt värde från kund-modellen till rätt fält i formuläret
  - Formuläret ska förpopuleras med befintliga värden (GET i Accountprovider ska användas)
  - Fälten i formuläret ska inte vara ändringsbara förens admin tryckt på edit-knappen

- [ ] Skapa en edit-knapp i formuläret
  - Knappen ska göra fälten för kundens uppgifter ändringsbara
  - Lägg till en save-knapp som påkallar Update funktionen i AccountProvider

- [ ] Det ska finnas en raderingsknapp som tar bort kunden ur systemet
  - Kund Id ska skickas in i DELETE i AccountProvider

- [ ] Skapa validering för formuläret
  - Formuläret ska ha korrekt validering för email 
  - Formuläret ska ha korrekt validering för telefonnummer
  - Formuläret ska ha korrekt validering för tvingande fält
  - Formuläret ska inte tömmas om validering inte uppfylls utan admin ska ha chans att rätta till fältet

- [ ] Det ska finnas en Orders-knapp
  - Vid tryck av denna så ska en ny vy visas som listar upp kundens ordrar

- [ ] Visa statuskoder som meddelande för admin
  - Meddelandena ska vara i klar text t.ex vid retur av statuskod 200 = "Uppdatering lyckades" eller  "Kund borttagen"

## Acceptanskriterier
1. En admin ska kunna uppdatera en kunds uppgifter via ett formulär
2. Det ska finnas korrekt validering till fälten
3. Det ska finnas en knapp som visar kundens ordrar
4. Det ska visas ett meddelande beroende på utfall

### **Lyckad uppdatering**
  Förutsättningar: 
  - Admin är inloggad
  - Admin väljer att uppdatera en befintlig kund via formuläret
  - Värdena i fälten är korrekt samt validerade
          
**Steg**
1. Ändra ett värde i ett fält för en kund
2. Klicka på submit knappen så formuläret skickas iväg
           
**Förväntat resultat**
  - En kunds uppgifter har uppdaterats
  - Ett meddelande visas som informerar admin att det gått igenom

### **Ett värde är inte korrekt**
Förutsättningar: 
  - Admin är inloggad
  - Admin skriver in fel email t.ex

**Steg**
  1. Ändra ett värde
  2. Ett av värdena i fältet är inkorrekt (t.ex email utan "@")

**Förväntat resultat**
  - Ett felmeddelande visas som informerar admin om vilket/vilka värde som inte är korrekt och hur det ska skrivas för att validering ska gå igenom
  - Admin ska ha möjlighet att rätta till fältet utan att allt försvinner

### **Admin väljer att radera kund**
Förutsättningar: 
  - Admin väljer en specifik kund att radera
  - Kund ID skickas in i DELETE i AccountProvider

**Steg**
1. Tryck på customers knappen från huvudsidan
2. Tryck på radera-knappen på en specifik kund

**Förväntat resultat**
  - Kund raderas ur systemet och ett meddelande visas att detta har lyckats

### **Admin väljer att radera kund men Kund ID:t skickas inte med**
Förutsättningar: 
  - Admin väljer en specifik kund att radera

**Steg**
1. Tryck på customers knappen från huvudsidan
2. Tryck på radera-knappen på en specifik kund

**Förväntat resultat**
  - Meddelande visas att något har gått fel och kund inte har raderats
