### ISSUE TITLE
Som Admin vill jag kunna få en lista på kunder

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#8]
## Tasks
- [ ] Skapa en vy som listar upp alla kunder
  - Det ska finnas en kolumn för förnamn
  - Det ska finnas en kolumn för efternamn
  - Det ska finnas en kolumn för KundId
  - Det ska finns en kolumn för kundens email

- [ ] Alla kunder hämtas via AccountProvider
  - GetAll funktionen påkallas från AccountProvider

- [ ] Paginering ska finnas
  - Högst 50 kunder per sida

- [ ] Det ska finnas en knapp per rad som ger admin möjlighet att editera kundens uppgifter
  - KundId ska skickas med som Data så att rätt kund hämtas i nästa vy
  - Denna knapp ska dirigera en vidare till vyn för en specifik kund

- [ ] Det ska finnas en knapp per rad som ger admin möjlighet att radera kunden
  - Kund Id ska skickas in i DELETE i AccountProvider

- [ ] Det ska finnas funktionalitet att filtrera
  - Man ska kunna filtrera efter datum kunden är skapad
  - Man ska kunna filtrera efternamn i bokstavsordning

- [ ] Visa statuskoder som meddelande för admin
  - Meddelandena ska vara i klar text t.ex vid retur av statuskod 200 = "Kund borttagen" eller "Något gick fel"

## Acceptanskriterier
1. En admin ska via denna sida kunna se alla kunder
2. Paginering på max 50 per sida
3. Möjlighet att gå vidare till en specifik vy för kund via en edit-knapp eller dylikt
4. Möjlighet att radera en kund ur systemet m.h.a en knapp
5. Kunna filtrera efter datum och namn
### **Admin ser alla kunder**
  Förutsättningar: 
  - Admin väljer att gå in i vyn för alla kunder
          
**Steg**
1. Tryck på customers knappen från huvudsidan
2. Admin filtrerar efter senast tillagd kund
           
**Förväntat resultat**
  - Alla kunder visas i en lista
  - Listan är filtreringsbar efter senast tillagd

### **Admin väljer att editera kund**
Förutsättningar: 
  - Admin väljer en specifik kund att editera
  - Kund ID skickas med

**Steg**
1. Tryck på customers knappen från huvudsidan
2. Tryck på edit-knappen på en specifik kund

**Förväntat resultat**
  - Dirigeras om till vyn för en specifik kund med förpopulerade fält

### **Admin väljer att editera kund men Kund ID:t skickas inte med**
Förutsättningar: 
  - Admin väljer en specifik kund att editera

**Steg**
1. Tryck på customers knappen från huvudsidan
2. Tryck på edit-knappen på en specifik kund

**Förväntat resultat**
  - Dirigeras om till vyn för en specifik kund men fälten i nästa vy är tomma

### **Admin väljer att radera kund**
Förutsättningar: 
  - Admin väljer en specifik kund att radera
  - Kund ID skickas in i DELETE i AccountProvider

**Steg**
1. Tryck på customers knappen från huvudsidan
2. Tryck på radera-knappen på en specifik kund

**Förväntat resultat**
  - Kund raderas ur systemet och ett meddelande visas att detta har lyckats

### **Admin väljer att radera kund men Kund ID:t skickas inte med**
Förutsättningar: 
  - Admin väljer en specifik kund att radera

**Steg**
1. Tryck på customers knappen från huvudsidan
2. Tryck på radera-knappen på en specifik kund

**Förväntat resultat**
  - Meddelande visas att något har gått fel och kund inte har raderats
