### ISSUE TITLE
Som Admin vill jag kunna se en kunds ordrar

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_Backoffice#9]
## Tasks
- [ ] Det ska finnas en vy som listar upp kundens allas ordrar
  - Det ska finnas en kolumn för kundens förnamn
  - Det ska finnas en kolumn för kundens efternamn
  - Det ska finnas en kolumn för kundens email
  - Det ska finnas en kolumn för orderID
  - Det ska finnas en kolumn för total-pris
  - Det ska finnas en kolumn för order-status

- [ ] All orders ska hämtas via OrderProvider
  - Använd dig av email för att hitta en kunds ordrar i Orderprovider
  - Använd dig av GetAllForCustomer i OrderProvider

- [ ] Order-status kolumnen ska kunna filtreras
  - Det ska gå att stapla ordrarna beroende på om det är en aktiv, pågående, avslutad order etc

- [ ] Det ska finnas en vy för en specifik order
  - Det ska gå att trycka på en order i listvyn som dirigerar en vidare till den specifika ordern
  - Använd dig av GET i OrderProvider m.h.a OrderId för att hitta dess information
  - Allt information i denna order ska listas i denna vyn

- [ ] Visa statuskoder som meddelande för admin
  - Meddelandena ska vara i klar text t.ex vid retur av statuskod 404 = "Inga ordrar funna"

## Acceptanskriterier
1. Ska finnas en vy som tydligt listar upp alla ordrar en kund har
2. Det ska gå att trycka på en order som visar en specifik order med fler detaljer
3. Meddelanden ska visas beroende på utfall

### **Lyckad visning av ordrar**
  Förutsättningar: 
  - Admin trycker på orders knappen i vyn för specifik kund

          
**Steg**
1. Välj en specifik kund
2. Tryck på orders knappen

           
**Förväntat resultat**
  - En ny vy visas med kundens alla ordrar

### **Det finns inga ordrar att hämta**
Förutsättningar: 
- Admin trycker på orders knappen i vyn för specifik kund

**Steg**
1. Välj en specifik kund
2. Tryck på orders knappen
3. Kunden har inga ordrar att lista

**Förväntat resultat**
  - Visa ett meddelande som informerar admin att kunden inte har några ordrar
